version: '3.4'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webflux
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
    networks:
      - webflux-network

networks:
  webflux-network:
    driver: bridge
