spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  datasource:
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
